run-cli:
	docker compose run --rm common sh

test:
	docker compose run --rm common yarn test

install-deps:
	docker compose run --rm common yarn install

lint:
	docker compose run --rm common npm run lint

lint-fix:
	docker compose run --rm common npm run lint:fix

build:
	docker compose build
