---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.1.1
#    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.1.1
#    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  lenses:
    image: lensesio/lenses:5.0.1
    environment:
      LENSES_PORT: 9991
      LENSES_SECURITY_USER: admin
      LENSES_SECURITY_PASSWORD: admin
    volumes:
      - ./data/lenses/storage:/data/storage
      - ./data/lenses/plugins:/data/plugins
      - ./data/lenses/logs:/data/logs
      - ./data/lenses/kafka-streams-state:/data/kafka-streams-state
    ports:
      - 9991:9991
      - 9102:9102

networks:
  default:
    external:
      name: jira-popug
