version: '3'

services:
  tasks-database:
    image: postgres:14.2-alpine
    ports:
      - 5433:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: tasks
      POSTGRES_PASSWORD: tasks

  tasks-service:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../common:/opt/common
      - ./:/opt/app
    ports:
      - 3001:3000
    environment:
      - DB_HOST=tasks-database
      - DB_DATABASE=tasks
      - DB_USER=tasks
      - DB_PASSWORD=tasks
      - DB_DEBUG=${DB_DEBUG:-false}
      - LOG_LEVEL=info

networks:
  default:
    external:
      name: jira-popug
